---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: airbyte-orbit-certificate
  namespace: emissary
spec:
  secretName: airbyte-orbit-tls-1
  issuerRef:
    name: letsencrypt-orbit-issuer
    kind: ClusterIssuer
  dnsNames:
  - airbyte-orbit.fannylimin.my.id

