---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-orbit-issuer
spec:
  acme:
    email: fannyleemin@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-orbit
    solvers:
    - http01:
        ingress:
          class: nginx
      selector: {}