---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: airbyte-host
  namespace: emissary
spec:
  hostname: airbyte-orbit.fannylimin.my.id
  acmeProvider:
    authority: none
  requestPolicy:
    insecure:
      action: Route
  tlsSecret:
    name: airbyte-orbit-tls-1
