# source: https://github.com/airbytehq/airbyte-platform/blob/main/charts/airbyte/values.yaml

global:
  airbyteUrl: https://airbyte.fannylimin.my.id

webapp:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 5
    successThreshold: 1

cron:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 5
    successThreshold: 1

server:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 300
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 5
    successThreshold: 1

worker:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 5
    successThreshold: 1

workload-launcher:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 5
    successThreshold: 1

workload-api-server:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 5
    successThreshold: 1

connector-builder-server:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 5
    successThreshold: 1
