# source: https://github.com/airbytehq/airbyte-platform/blob/main/charts/airbyte/values.yaml

global:
  airbyteUrl: airbyte.fannylimin.my.id

webapp:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 200
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 5
    successThreshold: 1
  resources:
    limits:
       cpu: 200m
       memory: 400Mi
    requests:
       memory: 256Mi
       cpu: 100m

cron:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 200
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 5
    successThreshold: 1
  resources:
    limits:
       cpu: 300m
       memory: 500Mi
    requests:
       memory: 256Mi
       cpu: 250m

server:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 300
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 5
    successThreshold: 1
  resources:
    limits:
       cpu: 300m
       memory: 1Gi
    requests:
       memory: 500Mi
       cpu: 250m

worker:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 200
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 5
    successThreshold: 1
  resources:
    limits:
       cpu: 100m
       memory: 500Mi
    requests:
       memory: 256Mi
       cpu: 50m

workload-launcher:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 300
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 5
    successThreshold: 1
  resources:
    limits:
       cpu: 300m
       memory: 500Mi
    requests:
       memory: 256Mi
       cpu: 250m

workload-api-server:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 200
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 5
    successThreshold: 1
  resources:
    limits:
       cpu: 200m
       memory: 500Mi
    requests:
       memory: 500Mi
       cpu: 100m

connector-builder-server:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 200
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 5
    successThreshold: 1
  resources:
    limits:
       cpu: 200m
       memory: 1Gi
    requests:
       memory: 500Mi
       cpu: 100m
